version: '3.8'

volumes:
  postgres-data:

services:
  app:
    container_name: javadev
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
        DB_PASS: postgres
        DB_NAME: postgres
        DB_USER: postgres
        DB_HOST: postgresdb
        DB_PORT: 5432
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

    depends_on:
      - db
    networks:
      - backend-net

  db:
    container_name: postgresdb
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - backend-net
