name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, analyze and release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Get next version
        id: version
        run: |
          LATEST_TAG=$(git tag -l "v*" --sort=-version:refname | head -n1)
          
          if [ -z "$LATEST_TAG" ]; then
            NEW_VERSION="1.0.0"
          else
            VERSION=${LATEST_TAG#v}
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          
            PATCH=$((PATCH + 1))
          
            if [ $PATCH -gt 9 ]; then
              MINOR=$((MINOR + 1))
              PATCH=0
            fi
          
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          fi
          
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Next version: $NEW_VERSION"

      - name: Update pom.xml version
        run: |
          mvn versions:set -DnewVersion=${{ steps.version.outputs.version }}
          mvn versions:commit

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=auth-ms \
            -Dsonar.projectName='auth-ms'

      - name: Check SonarQube Quality Gate
        run: |
          sleep 15
          STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
            "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=auth-ms" \
            | jq -r '.projectStatus.status')
          
          if [ "$STATUS" != "OK" ]; then
            exit 1
          fi

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Create Git tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            ## Changes
            - Automated release from main branch
            - SonarQube analysis passed ✅
            
            ## Artifacts
            - auth-ms-${{ steps.version.outputs.version }}.jar
          draft: false
          prerelease: false

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/auth-ms-${{ steps.version.outputs.version }}.jar
          asset_name: auth-ms-${{ steps.version.outputs.version }}.jar
          asset_content_type: application/java-archive
